// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    Api: typeof import('./src/components/Home/Main/Api.vue')['default']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Collapse: typeof import('./src/components/Home/Collapse.vue')['default']
    Data: typeof import('./src/components/Home/Main/Data.vue')['default']
    Delete: typeof import('./src/components/Home/Main/Delete.vue')['default']
    Get: typeof import('./src/components/Home/Main/Get.vue')['default']
    Headers: typeof import('./src/components/Home/Main/Headers.vue')['default']
    Highlight: typeof import('./src/components/Home/Code/Highlight.vue')['default']
    Index: typeof import('./src/components/Home/Index.vue')['default']
    JsonEditor: typeof import('./src/components/Home/Code/JsonEditor.vue')['default']
    Main: typeof import('./src/components/Home/Main.vue')['default']
    Menu: typeof import('./src/components/Home/Menu.vue')['default']
    Post: typeof import('./src/components/Home/Main/Post.vue')['default']
    Put: typeof import('./src/components/Home/Main/Put.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
